### ISSUE TITLE
Doesn't seem to work with  Android(version 4.4)

### ISSUE THREAD

**Issue by ultrasamad** [kevguy/Deslider#2]
When I tested it with android version 6, it works without any problem. But with android version 4, 

I get "Uncaught SyntaxError: Unexpected identifier on line 183".  And line 183 is pointing to caption: caption.  Here is my code

```
function createGallery(images, caption, container)
{
    "use strict";

    var obj = [];
    images.map(function(link, idx){
      obj.push({
        link,
        caption: caption
      });
    })
    new Deslider(obj, container);
}
```

**Comment by kevguy** [comment]
I don't have an Android 4 device, so replicating the problem is a bit tricky for me. Can you tell me more? My initial thought is maybe replacing `caption: caption` with `caption` and see if the problem can be fixed, as a lot of `Uncaught SyntaxError` are related to strict mode and ES6 stuff.

**Comment by ultrasamad** [comment]
Yeah. I used an Android emulator for the testing.  I rather tried pre-ES6 syntax {link: link, caption: caption} and the error is gone. 

One other problem is that the images in the slide shows doesn't change 4.  But you can see the dots paginators changing positions. It just stands at the same image.

Vendor prefixes in the css file only makes the slider works in android 5 upwards.

I suspect the Deslider.js uses CSS3 features for the transition:
`_this4.sliderEl.style.transform = 'translateX(' + transformPercentage + '%)';`  which I believe is the cause. Since the android device browsers doesn't understand CSS3 without vendor prefixes.
